name: genesis_workspace
description: "Genesis Workspace application."
publish_to: 'none'

version: 1.4.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #State management:
  flutter_bloc: ^9.1.1

  #api
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1

  #di
  injectable: ^2.5.0
  get_it: ^8.0.3

  #local db/storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  drift: ^2.28.1
  drift_flutter: ^0.2.5

  #router
  go_router: ^16.0.0
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1

  #ui
  flutter_svg: ^2.2.0
  visibility_detector: ^0.4.0+2
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  skeletonizer: ^2.1.0+1
  in_app_idle_detector: ^0.0.1
  flutter_widget_from_html: ^0.17.0
  fwfh_cached_network_image: ^0.16.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  cupertino_icons: ^1.0.8
#  flutter_inappwebview: ^6.1.5
  scroll_to_index: ^3.0.1
  audioplayers: ^6.5.0
  keyboard_height_plugin: ^0.1.5
  package_info_plus: ^8.0.2


  #data
  equatable: ^2.0.7
  intl: ^0.20.2
  path_provider: ^2.1.5
  emoji_picker_flutter: ^4.3.0
  flutter_emoji: ^2.5.1
  flutter_popup: ^3.3.9
  convert: ^3.1.2
  cryptography: ^2.7.0
  file_picker: ^10.3.3
  mime: ^2.0.0
  image_picker: ^1.2.0
  super_drag_and_drop: ^0.9.1
  path: ^1.9.1
  cross_file: ^0.3.4+2
  super_clipboard: ^0.9.1

  #utils
  desktop_updater:
    git:
      url: https://github.com/infraguys/flutter_desktop_updater.git
      ref: fix/no-cryptography-plus

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_lint: ^0.2.0-dev
  retrofit_generator: ^9.2.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  flutter_gen_runner: ^5.10.0
  slang_build_runner: ^4.7.0
  drift_dev: ^2.28.0

dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      ref: patch-2
      path: flutter_secure_storage_linux
  flutter_secure_storage_platform_interface: 2.0.0

flutter_gen:
  integrations:
    image: true
    flutter_svg: true
  assets:
    exclude:
      - assets/audio/pop.wav

flutter:
  uses-material-design: true
  default-flavor: stage
  assets:
    - assets/images/
    - assets/audio/pop.wav
    - assets/audio/whoop.wav
#    - assets/sqlite3.wasm
#    - assets/drift_worker.dart.js

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/Noto_Color_Emoji/Noto-COLRv1.ttf
    - family: AppleEmoji
      fonts:
        - asset: assets/fonts/Apple_Emoji/AppleColorEmoji.ttf
