name: genesis_workspace
description: "Genesis Workspace application."
publish_to: 'none'

version: 1.8.1+7

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #State management:
  flutter_bloc: ^9.1.1

  #api
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1

  #di
  injectable: ^2.6.0
  get_it: ^8.0.3

  #local db/storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  drift: ^2.28.1
  drift_flutter: ^0.2.5

  #router
  go_router: ^16.0.0
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1

  #ui
  flutter_svg: ^2.2.0
  visibility_detector: ^0.4.0+2
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  skeletonizer: ^2.1.0+1
  in_app_idle_detector: ^0.0.1
  flutter_widget_from_html: ^0.17.0
  fwfh_cached_network_image: ^0.16.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  cupertino_icons: ^1.0.8

  flutter_inappwebview: ^6.1.5
  audioplayers: ^6.5.0
  package_info_plus: ^8.0.2
  window_manager: ^0.3.9


  #data
  equatable: ^2.0.7
  intl: ^0.20.2
  path_provider: ^2.1.5
  emoji_picker_flutter: ^4.3.0
  flutter_emoji: ^2.5.1
  flutter_popup: ^3.3.9
  convert: ^3.1.2
  cryptography: ^2.7.0
  file_picker: ^10.3.3
  mime: ^2.0.0
  image_picker: ^1.2.0
  super_drag_and_drop: ^0.9.1
  path: ^1.9.1
  cross_file: ^0.3.4+2
  super_clipboard: ^0.9.1
  tar: ^2.0.1
  archive: ^4.0.7
  open_file: ^3.5.10
  file_saver: ^0.3.1
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  crypto: ^3.0.7
  flutter_local_notifications: ^19.5.0
  talker_flutter: ^5.1.9
  talker_dio_logger: ^5.1.9
  talker_bloc_logger: ^5.1.9
  scrollable_positioned_list: ^0.3.8
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_lint: ^0.3.3
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  json_serializable: ^6.11.1
  injectable_generator: ^2.9.1
  flutter_gen_runner: ^5.10.0
  slang_build_runner: ^4.7.0
  drift_dev: ^2.28.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
#      commit: f076cbb65b075afd6e3b648122987a67306dc298
#      ref: patch-2
      ref: f076cbb65b075afd6e3b648122987a67306dc298
      path: flutter_secure_storage_linux
  flutter_secure_storage_platform_interface: 2.0.0

flutter_gen:
  integrations:
    image: true
    flutter_svg: true
  assets:
    exclude:
      - assets/audio/pop.wav

desktop_updater:
  build_args:
    all:
      - --release
    linux:
      - -t
      - lib/prod.dart
      - --dart-define-from-file=env.json

flutter:
  uses-material-design: true
  default-flavor: stage
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/pop.wav
    - assets/audio/whoop.wav
#    - assets/sqlite3.wasm
#    - assets/drift_worker.dart.js

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/Noto_Color_Emoji/Noto-COLRv1.ttf
    - family: AppleEmoji
      fonts:
        - asset: assets/fonts/Apple_Emoji/AppleColorEmoji.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
